config/routes.rb
Rails.application.routes.draw do
  root 'admin#index'
  
  resources :customers
  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
    # 名前は必須入力かつ20文字以内
  validates :name , length: { maximum: 20 } , presence: true
  # 内容は必須入力かつ2文字以上30文字以下
  validates :zip , length: { minimum: 2, maximum: 30 } , presence: true
  validates :address1 , length: { minimum: 2, maximum: 30 } , presence: true
  validates :address2 , length: { minimum: 2, maximum: 30 } , presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @customers = Customer.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    
    def index
        @customers = Customer.all
    end
    
    def new
        @customer = Customer.new
    end
    
    def show
        @customer = Customer.find params[:id]
    end
    
    def edit
        @customer = Customer.find params[:id]
    end
    
    def create
        @customer = Customer.new(customer_params)
            if @customer.save
                redirect_to customer_path(@customer) , notice: 'メッセージを保存しました'
             else
                @customers = Customer.all
                flash.now[:alert] = "メッセージの保存に失敗しました。"
                render :new
            end
        
    end
    
    def update
        @customer = Customer.find params[:id]
        if @customer.update(customer_params)
            redirect_to @customer
        else
            render 'edit'
        end
    end
    def destroy
        @customer = Customer.find params[:id]
        @customer.destroy
        redirect_to customers_path, notice: '削除しました。'
    end
    
    private
    
    def customer_params
        params.require(:customer).permit(:name, :zip, :address1, :address2)
    end
    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Admin#index</h1>
</section>

<!-- Main content -->
<section class="content">
  <p>Find me in app/views/admin/index.html.erb</p>
  <%= link_to "顧客管理", customers_path %>
</section>

app/views/customers/edit.html.erb
<p>編集する</p>
<%= form_for(@customer) do |f| %>

    <% if @customer.errors.present? %>
        
          <%= alert %>
         
            <% @customer.errors.full_messages.each do |full_message| %>
              
                <%= full_message %>
              
            <% end %> 
          
        
     <% end %>

    名前：
    <%= f.text_field :name %>
    郵便番号：
    <%= f.text_field :zip %>
    都道府県：
    <%= f.text_field :address1 %>
    市町村：
    <%= f.text_field :address2 %>
    
    <%= f.submit %>
<% end %>

app/views/customers/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>顧客一覧</h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="box">
    <div class="box-header">
      <%= link_to "新規登録", new_customer_path %>
      <div class="box-tools">
        <div class="input-group" style="width: 150px;">
          <input type="text" name="table_search" class="form-control input-sm pull-right" placeholder="Search">
          <div class="input-group-btn">
            <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>
    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tr>
          <th>名前</th>
          <th>郵便番号</th>
          <th>都道府県</th>
          <th>市町村</th>
        </tr>
        <% @customers.each do |customer| %>
        <tr>
        <td><%= link_to customer.name, customer_path(customer) %></td>
        <td><%= customer.zip %></td>
        <td><%= customer.address1 %></td>
        <td><%= customer.address2 %></td>
        </tr>
        <% end %>
      </table>
    </div><!-- /.box-body -->
  </div><!-- /.box -->
</section>

app/views/customers/new.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>新規登録</h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="box">
    <div class="box-body">
      <%= form_for(@customer, html: { class: "form-horizontal" }) do |f| %>
        <% if @customer.errors.present? %>
           <%= alert %>
           <% @customer.errors.full_messages.each do |full_message| %>
             <%= full_message %>
          <% end %>
        <% end %>

        <div class="form-group">
          <label for="name" class="col col-xs-12 col-sm-4 col-md-3 control-label">お名前</label>
          <div class="col col-xs-5 col-sm-3 col-md-3">
            <input type="text" name="name1" id="name1" class="form-control" placeholder="姓">
          </div>
          <div class="col col-xs-5 col-sm-3 col-md-3">
            <input type="text" name="name2" id="name2" class="form-control" placeholder="名">
          </div>
          <div class="col-xs-offset-2 col-sm-offset-2 col-md-offset-3"></div>
        </div>

        <div class="form-group">
          <label for="kana" class="col-xs-12 col col-sm-4 col-md-3 control-label">お名前（フリガナ）</label>
          <div class="col col-xs-5 col-sm-3 col-md-3">
            <input type="text" name="kana1" id="kana1" class="form-control" placeholder="セイ">
          </div>
          <div class="col col-xs-5 col-sm-3 col-md-3">
            <input type="text" name="kana2" id="kana2" class="form-control" placeholder="メイ">
          </div>
          <div class="col-xs-offset-2 col-sm-offset-2 col-md-offset-3"></div>
        </div>

        <div class="form-group">
          <label for="zipcode" class="col col-xs-12 col-sm-4 col-md-3 control-label">郵便番号</label>
          <div class="col col-xs-7 col-sm-4 col-md-4">
            <div class="input-group">
              <span class="input-group-addon">〒</span>
              <%= f.text_field :zip, class: 'form-control' %>
            </div>
          </div>
          <div class="col-xs-offset-5 col-sm-offset-4 col-md-offset-5"></div>
        </div>

        <div class="form-group">
          <label for="pref" class="col col-xs-12 col-sm-4 col-md-3 control-label">住所</label>
          <div class="col col-xs-7 col-sm-4 col-md-3">
            <select name="pref" id="pref" class="form-control">
              <option value="北海道">北海道</option>
              <option value="青森県">青森県</option>
              <option value="岩手県">岩手県</option>
              <option value="宮城県">宮城県</option>
              <option value="秋田県">秋田県</option>
              <option value="山形県">山形県</option>
              <option value="福島県">福島県</option>
              <option value="茨城県">茨城県</option>
              <option value="栃木県">栃木県</option>
              <option value="群馬県">群馬県</option>
              <option value="埼玉県">埼玉県</option>
              <option value="千葉県">千葉県</option>
              <option value="東京都">東京都</option>
              <option value="神奈川県">神奈川県</option>
              <option value="新潟県">新潟県</option>
              <option value="山梨県">山梨県</option>
              <option value="長野県">長野県</option>
              <option value="富山県">富山県</option>
              <option value="石川県">石川県</option>
              <option value="福井県">福井県</option>
              <option value="岐阜県">岐阜県</option>
              <option value="静岡県">静岡県</option>
              <option value="愛知県">愛知県</option>
              <option value="三重県">三重県</option>
              <option value="滋賀県">滋賀県</option>
              <option value="京都府">京都府</option>
              <option value="大阪府">大阪府</option>
              <option value="兵庫県">兵庫県</option>
              <option value="奈良県">奈良県</option>
              <option value="和歌山県">和歌山県</option>
              <option value="鳥取県">鳥取県</option>
              <option value="島根県">島根県</option>
              <option value="岡山県">岡山県</option>
              <option value="広島県">広島県</option>
              <option value="山口県">山口県</option>
              <option value="徳島県">徳島県</option>
              <option value="香川県">香川県</option>
              <option value="愛媛県">愛媛県</option>
              <option value="高知県">高知県</option>
              <option value="福岡県">福岡県</option>
              <option value="佐賀県">佐賀県</option>
              <option value="長崎県">長崎県</option>
              <option value="熊本県">熊本県</option>
              <option value="大分県">大分県</option>
              <option value="宮崎県">宮崎県</option>
              <option value="鹿児島県">鹿児島県</option>
              <option value="沖縄県">沖縄県</option>
            </select>
          </div>
          <div class="col-xs-offset-5 col-sm-offset-4 col-md-offset-6"></div>
        </div>

        <div class="form-group">
          <div class="col col-sm-8 col-sm-offset-4 col-md-9 col-md-offset-3">
             <%= f.text_field :address2, class: 'form-control' %>
            <p class="help-block">住所は2つに分けてご記入ください。</p>
            <input type="text" name="addr2" id="addr2" class="form-control" placeholder="番地・ビル名">
            <p class="help-block">マンション名は必ず記入してください。</p>
          </div>
        </div>

        <div class="form-group">
          <label for="tel" class="col col-xs-12 col-sm-4 col-md-3 control-label">電話番号</label>
          <div class="col-xs-12 colcol-xs-10 col-sm-6 col-md-7">
            <div class="input-group">
              <input type="tel" name="tel1" id="tel1" class="form-control" placeholder="080">
              <span class="input-group-addon">-</span>
              <input type="tel" name="tel2" id="tel2" class="form-control" placeholder="0000">
              <span class="input-group-addon">-</span>
              <input type="tel" name="tel3" id="tel3" class="form-control" placeholder="0000">
            </div>
          </div>
          <div class="col-xs-offset-2 col-sm-offset-2 col-md-offset-2"></div>
        </div>

        <div class="form-group">
          <label for="email" class="col col-xs-12 col-sm-4 col-md-3 control-label">メールアドレス</label>
          <div class="col col-xs-12 col-sm-6 col-md-7">
            <input type="email" name="email" id="email" class="form-control" placeholder="メールアドレスを入力してください">
          </div>
          <div class="col-xs-offset-0 col-sm-offset-2 col-md-offset-2"></div>
        </div>

        <div class="form-group">
          <div class="col col-xs-9 col-xs-offset-3 col-sm-8 col-sm-offset-4 col-md-9 col-md-offset-3">
            <button type="submit" class="btn btn-success btn-lg">　確　認　</button>
          </div>
        </div>

        <script type="text/javascript">
            jQuery(function($){
              // 郵便番号入力による住所自動入力
              $('#customer_zip').change(function(){
                var zip = $(this).val();
                var url = 'http://api.zipaddress.net?callback=?';
                var query = {'zipcode': zip};
                $.getJSON(url, query, function(json){
                  $('#pref').val(json.pref);
                  $('#addr1').val(json.address);
                });
              });
            });
        </script>

    </div>
  </div><!-- .box -->


<div class="container">
  <div class="row">
    <div class="col-sm-2">名前：</div>
    <div class="col-sm-10 form-inline" style="padding: 3px;">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">郵便番号：</div>
    <div class="col-sm-10 form-inline" style="padding: 3px;">
      <%= f.text_field :zip, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">都道府県：</div>
    <div class="col-sm-10 form-inline" style="padding: 3px;">
      <%= f.text_field :address1, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">市町村：</div>
    <div class="col-sm-10 form-inline" style="padding: 3px;">
      <%= f.text_field :address2, class: 'form-control' %>
    </div>
  </div>
</div>

  <div class="text-center" style="padding: 30px;">
   <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

</section>

app/views/customers/show.html.erb
<div id="page">
    <div class="container">
      <h1>登録確認画面</h1>
      <%= link_to "編集する", edit_customer_path %>
<%= link_to "削除する", customer_path, method: :delete, data: { confirm: "本当によろしいですか？"} %>
      <div class="row">
        <div class="col-sm-9">
            <div class="form-group">
              <label for="input-name" class="col-sm-2 control-label">お名前</label>
              <div class="col-sm-10">
                <%= @customer.name %>
              </div>
            </div>
            <div class="form-group">
              <label for="input-mail" class="col-sm-2 control-label">郵便番号</label>
              <div class="col-sm-10">
                <%= @customer.zip %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">都道府県</label>
              <div class="col-sm-10">
                <%= @customer.address1 %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">市町村</label>
              <div class="col-sm-10">
                <%= @customer.address2 %>
              </div>
            </div>
        </div>
      </div>
      
<%= link_to "一覧に戻る", customers_path %>
    </div><!-- /container -->
  </div><!-- /page -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rayhope</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
   <link rel="stylesheet" href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
   <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.3/css/AdminLTE.min.css">
   <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.3/css/skins/_all-skins.min.css">
  <%= csrf_meta_tags %>
</head>
<body class="skin-blue fixed">
 <div class="wrapper">
   <header class="main-header">
     <a href="/" class="logo">Rayhope</a>
     <nav class="navbar navbar-static-top" role="navigation">
        <a class="sidebar-toggle" href="#" data-toggle="offcanvas" role="button"></a>
 
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
          </ul>
        </div>
     </nav>
   </header>
 
   <aside class="main-sidebar">
     <section class="sidebar">
       <ul class="sidebar-menu">
         <li class="header">メニュー</li>
         <li>
           <%= link_to(customers_path) do %>
             <i class="fa fa-circle-o text-info"></i>メニュー 1
           <% end %>
         </li>
         <li>
           <%= link_to(customers_path) do %>
             <i class="fa fa-circle-o text-warning"></i>メニュー 2
           <% end %>
         </li>
         <li>
           <%= link_to(customers_path) do %>
             <i class="fa fa-circle-o text-danger"></i>メニュー 3
           <% end %>
         </li>
       </ul>
     </section>
   </aside>
 
   <div class="content-wrapper">
     <% if notice %>
       <%= notice %>
    <% end %>
    <%= yield %>
   </div>
</div><!-- .wrapper -->
 
 <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
 <script src="//cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.3/js/app.min.js"></script>

</body>
</html>